language: python
python:
- 2.7
- 3.4
- 3.5
install:
- pip install -r test-requirements.txt
- pip install -r requirements.txt
- pip install .
- pip install coveralls
script:
- coverage run --source pyEXOS.exos test/test_unittest.py -v
after_success: coveralls
deploy:
  provider: pypi
  user: fooelisa
  password:
    secure: ESyAM7x87byzCP2KExucUsM4ONLkA1pm/JynDxNIRjqOmjz3yMDKgQkpMW/ACVFDJNFFtoNd/6kiRUS0cY2wjAYkplo0cUDfQDK4cNjwFEmvnVjaAvecGZbVOiYkiyelO1x0h1MpJV2J9TPrfYBiRmiXzdOlXNHUl17JXGh/xo8wSXf4UtqGZ12ofVS92MvtRCqC+PCwdb7X1bOwFlxPfJIUEgY7k47qhdOr1/+t8BxilJG/ua0iKQC15c5IPENh4XWGl6j+S0Fp6a0SgF0k0GrvKyJHI9pVSoIfi4OGb6WgqrgD3eM0zWoSwsmKNegNWm6qc0RjeQheelY4xAIr2OB+ak25JVvMWdyAFiN0tRK8bkmCCcyZgZgCoYgJCjMb8jD+JH3TwuXzU/UUPemb0u6VcVZlqSP6CNlRkfTiZWrbIpJswDWwRNb8K3wdFqDH/JaWta+XtvzHl8pEEz1qDNok3PEfB83rENTANNh0zDmmPCc1bJF228mhLC+O37faVhUOR2nimHw0eQYLKvZQJbEE4IQPbVYjvhGJNcdIHikM0AOMBCt9ZOxpSH1l0KcRKhHt2L0kwh8jIrlDYbfJ6F3h7cRTw8NQSAXAplg76GUUx0G2soAagN557RU6MBE3JyPnq1UcV3hxTTNCC72QekerNwbjrzYAF4JhytB8EmM=
  on:
    tags: true
    branch: master
